### ISSUE TITLE
add to ios store

### ISSUE THREAD

**Issue by paulchrisluke** [pcl-labs/BrowTricks#396]
@joeelia can you help me with this?

**Comment by joeelia** [comment]
No. Its a lot of work to do this and last time nobody bothered to look at my PR @paulchrisluke

**Comment by bamboochow** [comment]
Screenshots are included here: 
[App Store Screenshots.zip](https://github.com/whynotearth/BrowTricks/files/5407839/App.Store.Screenshots.zip)
